spring:
  application:
    name: sf-food-trucks
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/testdb
#    username: root
#    password: 123456
  data:
    jpa:
      repositories:
        bootstrap-mode: default

server:
  port: 8081
